name: Tag WorkFlow

on:
  push:
    tags:
      - v*

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: vodea-cloud/vodeamail-public
  REGISTRY_HOSTNAME: asia.gcr.io

jobs:
  app-tests:
    name: Setup CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: yarn install
#      - name: Execute tests (Unit and e2e tests)
#        run: yarn test --watchAll=false
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    needs: [app-tests]
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: |
          yarn install
          yarn build
      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCR_KEY }}
      - run: gcloud auth configure-docker
      - name: Build
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build . -t "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":latest
