name: Tag WorkFlow

on:
  push:
    tags:
      - v*

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: vodea-cloud/vodeamail-public
  REGISTRY_HOSTNAME: asia.gcr.io

jobs:
  app-tests:
    name: Setup CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: homestead
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: yarn install
      - name: Execute tests (Unit and e2e tests)
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_DATABASE: homestead
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: yarn test --forceExit --detectOpenHandles
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    needs: [app-tests]
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: |
          yarn install
          yarn build
      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.1
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCR_KEY }}
      - run: gcloud auth configure-docker
      - name: Build
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build . -t "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE":latest
